name: Update DB

on:
  schedule:
    # - cron: '0 5 * * *'  # Runs the workflow at 12:00 AM EST (5:00 AM UTC)
    # - cron: '0 17 * * *' # Runs the workflow at 12:00 PM EST (5:00 PM UTC)
    - cron: '0 0,12 * * *'  # Runs the workflow at 12:00 AM and 12:00 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you have dependencies, list them here, e.g.,
          pip install -r requirements.txt

      - name: Run script
        run: python python/stalk-backfill.py
